### ISSUE TITLE
R.A.T. (Remote Access Trojan)

### ISSUE THREAD

**Issue by cheeziest** [colorblindness/3arthh4ck#3]
I have reason to believe this jar file (3arthh4ck) contains malicious code similar to that of a RAT (Remote Access Trojan), a malicious program that, unbeknownst to the user, opens a back door in the users computer, allowing the perpetrator/s full full access to the user’s PC (Personal Computer.) I will be contacting the appropriate authorities and you will be punished greatly for this despicable crime.

**Comment by colorblindness** [comment]
Factually incorrect.

**Comment by ssllllll** [comment]
🤡

**Comment by Doogie13** [comment]
🤡 actally check the code first lmao (idk if its safe, just pointing out that assuming so without _any evidence_ is misleading)

**Comment by ssllllll** [comment]
Ofc i did? Anyway im not gonna use it just in chase lols

**Comment by AnotherNoName** [comment]
😭😭😭

**Comment by nachos1234** [comment]
not a single person would be dumb enough to put a RAT in their software and make it open-source, dumbass
