### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by codingfirewastaken** [colorblindness/3arthh4ck#34]
EarthHack isnt installing
Heres what i did:
1. installed the installer
2. clicked on forge 1.12
3. pressed install
4. launched minecraft
5. tried to bind clickgui (didnt work because it wasnt installed)

**Comment by Torono909** [comment]
Put 3arthh4ck thing in .minecraft/mods and run forge 1.12.2 not 1.12

**Comment by codingfirewastaken** [comment]
k

**Comment by codingfirewastaken** [comment]
thx it worked

**Comment by ataniii** [comment]
can i use it with future
