### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by shxrkyy** [colorblindness/3arthh4ck#37]
The code has too much errors for the building process with gradle to continue. I have gone through so many ways of building and cannot get it. Thanks, shxrkyy / dylxn

**Comment by mdo992** [comment]
all you need to do is
1. clone using git
2. open it in intellij
3. run the setupDecompWorkspace
4. create a file named `version` and put a version number in
5. run the build task
6. mod is in `build/libs` with `release` in the name 😱😱

**Comment by shxrkyy** [comment]
holy tysm
ima try it rn
