### ISSUE TITLE
Replay Mod Mixin

### ISSUE THREAD

**Issue by GerroPogi** [colorblindness/3arthh4ck#41]
I want to do a montage with 3arthh4ack, but it doesn't work with replay mod. Can you fix this?

When I ran it will replay mod, it crashes.

**Comment by GerroPogi** [comment]
Sorry, I just think it might be impractical since you can run it yourself, and the problem is the mixin as explained so you won't need to read the crash log.

**Comment by 3arthqu4ke** [comment]
but im lazy I dont want to run it myself and "problem is with mixin" doesn't narrow it down at all :)
