### ISSUE TITLE
Media module shows name in command autocomplete

### ISSUE THREAD

**Issue by wiiyou** [colorblindness/3arthh4ck#46]
Whenever I type a command and press tab on parameter that needs a player name, it will show my real ign with it. For example, typing "/ignore " and pressing tab, it will show my ign.

**Comment by 3arthqu4ke** [comment]
Maybe Im dumb but I cant recreate this. Can u send a screenshot/video or something so I can get a better idea? Do you use other mods beside 3arthh4ck?

**Comment by 3arthqu4ke** [comment]
Fixed [here](https://github.com/3arthqu4ke/3arthh4ck). Need to build it tho
