### ISSUE TITLE
Lock issue or something.

### ISSUE THREAD

**Issue by owowowowowo-png** [colorblindness/3arthh4ck#47]
I don't really know how to explain it. A video will hopefully make you understand .
https://streamable.com/pqlki7

I tried without earthhack and just future client and everything was fine. no lock issue. but when i use earthhack (even with no modules on) still I have this issue. i checked if i was using any future modules as well if that was breaking it. I disabled every modules on both clients and still got this issue.

**Comment by mdo992** [comment]
bro wsp with that totem tho...?

**Comment by owowowowowo-png** [comment]
No idea random pack for a certain occasion

**Comment by mdo992** [comment]
btw i think you may want to open an issue [here](https://github.com/3arthqu4ke/3arthh4ck/issues)
