### ISSUE TITLE
Not able to jump

### ISSUE THREAD

**Issue by vanyamcr2** [colorblindness/3arthh4ck#48]
Sometimes when I log on to a server or even survival worlds At one point time I can't jump and when I press the space bar, my character jumps 0.3 blocks and teleports back When I leave a rejoin the issue goes away and then in some time comes back :( Putting my config as  well

File is in .txt rename to .json
[vanyamcr - Copy.txt](https://github.com/colorblindness/3arthh4ck/files/8680437/vanyamcr.-.Copy.txt)
n

**Comment by vanyamcr2** [comment]
> do you have godmod module turned on?

No

**Comment by master7720** [comment]
use this repo https://github.com/3arthqu4ke/3arthh4ck its an updated version

**Comment by vanyamcr2** [comment]
> use this repo https://github.com/3arthqu4ke/3arthh4ck its an updated version

alright

**Comment by 3arthqu4ke** [comment]
Cant recreate it with your config and 1.6.2, Use the latest version. Maybe it's NoRotate? It shouldn't be tho. Are you using other mods?

**Comment by vanyamcr2** [comment]
> Cant recreate it with your config and 1.6.2, Use the latest version. Maybe it's NoRotate? It shouldn't be tho. Are you using other mods?

Hmm I updated and the issue disappeared, Maybe it was anticheat or a bug in the old version
