### ISSUE TITLE
minecraft crashing

### ISSUE THREAD

**Issue by Righted1** [colorblindness/3arthh4ck#57]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:59)
	at me.earth.earthhack.impl.managers.config.helpers.MacroConfigHelper.readFile(MacroConfigHelper.java:19)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.read(AbstractConfigHelper.java:205)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.lambda$refresh$0(AbstractConfigHelper.java:100)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper$$Lambda$341/945944298.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at me.earth.earthhack.impl.managers.config.helpers.AbstractConfigHelper.refresh(AbstractConfigHelper.java:91)
	at me.earth.earthhack.impl.managers.config.ConfigManager.refreshAll(ConfigManager.java:54)
	at me.earth.earthhack.impl.managers.Managers.load(Managers.java:93)
	at me.earth.earthhack.impl.Earthhack.init(Earthhack.java:27)
	at net.minecraft.client.Minecraft.handler$initHook2$zzl000(Minecraft.java:3507)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by shxrkyy** [comment]
skill issue

**Comment by Doogie13** [comment]
Delete your config

**Comment by Uhhu738** [comment]
It's literally a virus-- it's *made* to crash so it can act

**Comment by Uhhu738** [comment]
Don't be rude, please. I have done my research about Phobos and I can \[partially] confirm that it's malware. I will correct my comment, but "not using a virus disguised as a client" doesn't help others who are vulnerable. Thank you for your 'patience'.

**Comment by Uhhu738** [comment]
While I am not a programmer myself, I'm positive it's a virus.
From what I know, the crashing is what activates the virus and it hasn't been fixed since the first Phobos. This could be due to just *not* being able to fix but it's probably intended [knowing Phobos].
It's suspiscous how that major issue never got fixed. The issue that supposedly enables the virus. Odd things associated with malware happen after the crash, so...

**Comment by 3arthqu4ke** [comment]
please, don't let the haters stop you! I want to hear more about your research

**Comment by master7720** [comment]
theres no way your being serious @Uhhu738

**Comment by Righted1** [comment]
> While I am not a programmer myself, I'm positive it's a virus. From what I know, the crashing is what activates the virus and it hasn't been fixed since the first Phobos. This could be due to just _not_ being able to fix but it's probably intended [knowing Phobos]. It's suspiscous how that major issue never got fixed. The issue that supposedly enables the virus. Odd things associated with malware happen after the crash, so...

did the you take your schizophrenia pills?

**Comment by Zane2b2t** [comment]
> Don't be rude, please. I have done my research about Phobos and I can [partially] confirm that it's malware. I will correct my comment, but "not using a virus disguised as a client" doesn't help others who are vulnerable. Thank you for your 'patience'.

LOL

**Comment by mdo992** [comment]
> My goal is to remove any maleficent projects from Github. Please cease making viruses and malware or anything of the sort. I report any virus I become aware of.

@Uhhu738 ’s bio. NO MORE 3ARTHH4CK 😭

**Comment by Uhhu738** [comment]
> > While I am not a programmer myself, I'm positive it's a virus.
> > From what I know, the crashing is what activates the virus and it hasn't been fixed since the first Phobos. This could be due to just _not_ being able to fix but it's probably intended [knowing Phobos].
> > It's suspiscous how that major issue never got fixed. The issue that supposedly enables the virus. Odd things associated with malware happen after the crash, so...
> 
> do you got schizophrenia?

Mf really closed the 'issue' and said I got schizophrenia brooo😂

**Comment by Uhhu738** [comment]
> 

Alright enjoy your virus that steals your info then 😃

**Comment by Uhhu738** [comment]
> > My goal is to remove any maleficent projects from Github. Please cease making viruses and malware or anything of the sort. I report any virus I become aware of.
> 
> @Uhhu738 ’s bio. NO MORE 3ARTHH4CK 😭

Alright enjoy your free virus then 😃

**Comment by Uhhu738** [comment]
> 

I ain't got schizophrenia the mf closed the issue or hid it because the comments are literally there 🤣

**Comment by Uhhu738** [comment]
> theres no way your being serious @Uhhu738

Oh I am

**Comment by Uhhu738** [comment]
> please, don't let the haters stop you! I want to hear more about your research

![image](https://user-images.githubusercontent.com/95198334/180660896-3bac8d88-c767-4032-bd4d-cb511209b84f.png)

**Comment by mdo992** [comment]
> > > My goal is to remove any maleficent projects from Github. Please cease making viruses and malware or anything of the sort. I report any virus I become aware of.
> > 
> > 
> > @Uhhu738 ’s bio. NO MORE 3ARTHH4CK 😭
> 
> Alright enjoy your free virus then 😃


https://user-images.githubusercontent.com/89719878/180661522-fb8028c7-1c54-4262-9534-ada7d64f4208.MOV

**Comment by Uhhu738** [comment]
https://user-images.githubusercontent.com/95198334/180665185-8ba7f331-29b8-4ab5-8532-5388ab70b4cc.mp4

**Comment by Uhhu738** [comment]
> > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> 
> okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.

I ain't stupid I know for a fact it wasn't targeted against me

**Comment by mdo992** [comment]
@Uhhu738 boutta send https://github.com/qqTechnologies/qqBackdoor

**Comment by Uhhu738** [comment]
> > > > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> > > 
> > > 
> > > okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.
> > 
> > 
> > I ain't stupid I know for a fact it wasn't targeted against me
> 
> Go outside you virgin.

Uno reverse card moment lmao

**Comment by Uhhu738** [comment]
> > > > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> > 
> > 
> > > 
> > 
> > 
> > > okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.
> > 
> > 
> > I ain't stupid I know for a fact it wasn't targeted against me
> 
> you sure you ain't stupid? can you show me where the so called malware is?

https://github.com/colorblindness/3arthh4ck/
 r i g h t h e r e

**Comment by mdo992** [comment]
> > > > > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> > > > 
> > > > 
> > > > okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.
> > > 
> > > 
> > > I ain't stupid I know for a fact it wasn't targeted against me
> > 
> > 
> > Go outside you virgin.
> 
> Uno reverse card moment lmao

who gave a 9 year old a github account?

**Comment by Zane2b2t** [comment]
> > > > > > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> > > > > 
> > > > > 
> > > > > okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.
> > > > 
> > > > 
> > > > I ain't stupid I know for a fact it wasn't targeted against me
> > > 
> > > 
> > > Go outside you virgin.
> > 
> > 
> > Uno reverse card moment lmao
> 
> who gave a 9 year old a github account?

Kilab gaming 🤣😂

**Comment by Uhhu738** [comment]
> > > > > > Tsugumomo.-.Kiriha.Laughing-DaQC9vSSSmo.online-video-cutter.com.mp4
> > > > > 
> > > > > 
> > > > > okay i admit it this client release was a targeted attack against uhhu738. he finally cracked the code.
> > > > 
> > > > 
> > > > I ain't stupid I know for a fact it wasn't targeted against me
> > > 
> > > 
> > > Go outside you virgin.
> > 
> > 
> > Uno reverse card moment lmao
> 
> who gave a 9 year old a github account?

a 9 year old definitely got oHare's

**Comment by shxrkyy** [comment]
@Uhhu738  good luck on removing jokes retard

**Comment by Uhhu738** [comment]
> @Uhhu738 good luck on removing jokes retard

Well then turns out all the devs of this Trojan are rude hoes

**Comment by Mathrandom7910** [comment]
> Well then turns out all the devs of this Trojan are rude hoes

:trollface:

**Comment by Uhhu738** [comment]
> > Well then turns out all the devs of this Trojan are rude hoes
> 
> :trollface: no way u aint

Wait
whAT

**Comment by mdo992** [comment]
> > > Well then turns out all the devs of this Trojan are rude hoes
> > 
> > 
> > :trollface: no way u aint
> 
> Wait whAT

can someone make this guy shut up he’s flooding my inbox

**Comment by Zane2b2t** [comment]
> > > > Well then turns out all the devs of this Trojan are rude hoes
> > > 
> > > 
> > > :trollface: no way u aint
> > 
> > 
> > Wait whAT
> 
> can someone make this guy shut up he’s flooding my inbox

Same

**Comment by Uhhu738** [comment]
> > > > > Well then turns out all the devs of this Trojan are rude hoes
> > > > 
> > > > 
> > > > :trollface: no way u aint
> > > 
> > > 
> > > Wait whAT
> > 
> > 
> > can someone make this guy shut up he’s flooding my inbox
> 
> Same

Okay I'll shut up
