### ISSUE TITLE
Fix Jitpack Builds

### ISSUE THREAD

**Issue by mdo992** [colorblindness/3arthh4ck#59]
can you fix jitpack's builds for earthhack at https://github.com/3arthqu4ke/3arthh4ck? both 1.6.2 and 1.6.3 builds are failing and aren't producing any artifacts since when you first added jitpack support

https://jitpack.io/com/github/3arthqu4ke/3arthh4ck/1.6.2/build.log and https://jitpack.io/com/github/3arthqu4ke/3arthh4ck/1.6.3-9e862dfb7c-1/build.log

i understand you may not want to work on it but please atleast fix this so people can make plugins for the latest version

posting here since 3arthqu4ke's repos is archived

**Comment by 3arthqu4ke** [comment]
```gradle
group: 'com.github.3arthqu4ke', name: '3arthh4ck', version: '9e862dfb'
```

That is 1.6.3, hope that suffices.

**Comment by mdo992** [comment]
> That is 1.6.3, hope that suffices.

Building 1.6.2 and 1.6.3 fails. I was asking if you can fix that.

**Comment by 3arthqu4ke** [comment]
https://jitpack.io/com/github/3arthqu4ke/3arthh4ck/9e862dfb/

This is a build of the latest commit in the 1.6.3 branch. It's the newest version of 3arthh4ck out there.

**Comment by mdo992** [comment]
> This is a build of the latest commit in the 1.6.3 branch. It's the newest version of 3arthh4ck out there.

It works now, thank you. How did you get it to work?

**Comment by 3arthqu4ke** [comment]
Added a jitpack yml to this repo: https://github.com/3arthqu4ke/3arthh4ck/blob/main/jitpack.yml that means that repo should work without me doing anything
