### ISSUE TITLE
This is 100% a virus, it logs a shit ton of info. Do not download this.

### ISSUE THREAD

**Issue by yaukari** [colorblindness/3arthh4ck#9]

**Comment by BerryPGz** [comment]
how yk? gopro admit it clean??

**Comment by u3o** [comment]
> 

yea he cant be wrong

**Comment by master7720** [comment]
weres the proof?

**Comment by HausemasterIssue** [comment]
if your talking about theia then please do your research.

coord checks are used in basically every client to place n break blocks.
reflections is just something used to better manipulate classes
web connection check you should look into where it is, not just blindly assume its a webhook

**Comment by Gopro336** [comment]
^^ still seen no proof of malicious code (cus there is none)

**Comment by colorblindness** [comment]
The web connection you are talking about is for our player lookup command https://github.com/colorblindness/3arthh4ck/blob/fc204c458face499813f0394d06c561bdf5a798d/src/main/java/me/earth/earthhack/impl/util/thread/LookUpUtil.java

**Comment by naygigga** [comment]
this boy prolly just watched fitmcs 1 year old phobos video and came here lel

**Comment by 5B0T** [comment]
It doesnt have a rat guys!

**Comment by master7720** [comment]
> if your talking about theia then please do your research.
> 
> coord checks are used in basically every client to place n break blocks. reflections is just something used to better manipulate classes web connection check you should look into where it is, not just blindly assume its a webhook

wdym theia is the best way to find out if a client has a virus1!!1!!!!111!
